# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('episode_link', models.CharField(max_length=300)),
                ('episode_num', models.IntegerField()),
                ('season', models.IntegerField()),
            ],
        ),
    ]
