# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episode_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='episode_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
