# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20161109_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
