# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20161109_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
