# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_serie_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
